# File derived from https://github.com/CTFd/CTFd/blob/d0813e72963e34773937ba41118a8b717a02a665/docker-compose.yml
# Copyright 2015-present CTFd LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# https://github.com/CTFd/CTFd/blob/14ea952a2a61f71affc1d869052b661b68f1d200/LICENSE

version: '2'

services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - ./data/CTFd/logs:/var/log/CTFd
      - ./data/CTFd/uploads:/var/uploads
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - ctfd


  db:
    image: mariadb:10
    restart: always
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:6-alpine
    restart: always
    volumes:
    - ./data/redis:/data
